### ISSUE TITLE
Can it be header only library?

### ISSUE THREAD

**Issue by apivovarov** [IMQS/utfz#2]
Many util libraries. e.g. `nlohmann/json` or even boost are "header only hpp" libs. Users do not need to explicitly mention `<lib>.cpp` file in the compilation command or `CMakeLists.txt`. Users just need to copy `<lib>.hpp` file to their project "include" folder and use "#include <lib>" in users cpp files.
Can we do the same with utfz?

**Comment by bmharper** [comment]
It could be for sure!
To avoid breaking compatibility with existing code, I think we should publish a `.h` file with a different name, but I can't think of a good name here...

**Comment by bmharper** [comment]
FINALLY... not sure if you're still interested @apivovarov... but I've added `utfz.hpp`, which is a header-only include.

**Comment by bmharper** [comment]
Done
