### ISSUE TITLE
Lack of supporting kanji chars since Unicode 8.0

### ISSUE THREAD

**Issue by ShikiSuen** [IMQS/utfz#3]
https://github.com/IMQS/utfz/blob/ffc39e5e8a6c6a7c10b8b859dd7f523f92764582/utfz.cpp#L14

This place needs to add minimum code points that is allowed to be encoded with 5 and 6 bytes.

**Comment by bmharper** [comment]
Hi @ShikiSuen,
I'm trying to find Unicode documentation indicating that we need 5 or 6 bytes, but so far I can't find anything. Most of the documents I can find seem to indicate that there are under 200k code points allocated. A 4 byte encoding is sufficient to represent about 1 million code points, so as far as I can tell, we're still far beneath that limit?

**Comment by ShikiSuen** [comment]
@bmharper Sorry for confusing you.
I knew less about how to process surrogate pairs when I was opening this issue thread which shouldn't exist.
